[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = [
    "-std=c++23",
    "-Wall",
    "-fsanitize=undefined",
    "-I",
    "/home/runner/work/library/library/include",
    "-I",
    "./include",
]
